### ISSUE TITLE
How to alias a package for Web?

### ISSUE THREAD

**Issue by ktprograms** [orYoffe/create-react-native-web-app#103]
Hi, how could I use something like [react-native-maps](https://github.com/react-native-maps/react-native-maps), which has a separate [web implementation](https://github.com/react-native-web-community/react-native-web-maps) (same API) and needs to be aliased (see the react-native-web-maps README.md)?

**Comment by orYoffe** [comment]
Ho @ktprograms ,

Sorry for the late response. You can change the webpack config with craco like this
https://github.com/orYoffe/rn-nav/blob/main/craco.config.js

I would check the craco npm package documentation.. but it's basically like any project started with create-react-app

**Comment by ktprograms** [comment]
Thanks, but I decided to `yarn eject` and manually edit the webpack config.
