### ISSUE TITLE
React Native is Outdated and vulnerable to ReDoS

### ISSUE THREAD

**Issue by ktprograms** [orYoffe/create-react-native-web-app#107]
In short, `react-native` should be updated to 0.64.1 at least. I'm just not sure if it's compatible with `react-native-web`

<img width="870" alt="Screenshot 2021-08-11 at 8 24 10 AM" src="https://user-images.githubusercontent.com/71804605/128951532-04e9b1e5-d1c7-4f5d-b1b8-ea41603a19ab.png">

**Comment by orYoffe** [comment]
just updated the template, should fix this
