### ISSUE TITLE
Error: Command failed: npx react-native init Test --template react-native-template-react-native-web

### ISSUE THREAD

**Issue by D4rxio** [orYoffe/create-react-native-web-app#108]
**Describe the bug**
Error: Command failed: npx react-native init Test --template react-native-template-react-native-web

**To Reproduce**
1. Use the command to create a new project: "npx create-react-native-web-app Test"
2. See error

**Expected behavior**
A new react-native with web application created as project stays

**Screenshots**
![image](https://user-images.githubusercontent.com/7951993/131252325-0ab900d7-b196-4c7e-8240-12e44dcd482f.png)
[yarn-error.log](https://github.com/orYoffe/create-react-native-web-app/files/7072608/yarn-error.log)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  - Windows 10 21H1
 - Browser [e.g. chrome, safari] - Opera GX - but didn't manage to start project yet
 - Version [e.g. 22] - 19043.1165
 - tried to use elevated powershell or standard

**Smartphone (please complete the following information):**   -  N/A

**Additional context**
Cannot create project unsing command

**Comment by orYoffe** [comment]
Hi @D4rxio 
I know this sounds funny, but could you try to run the command with

**Comment by orYoffe** [comment]
Hi @D4rxio did you use the package globally before? if so please uninstall it like this
`npm uninstall -g create-react-native-web-app`

**Comment by D4rxio** [comment]
Look like I did, I was trying several tutorials and could be that I messed everything 🤣

**Comment by orYoffe** [comment]
Thanks

**Comment by D4rxio** [comment]
works like a charm, didn't try uninstalling first. 
Thank you for support :)
