### ISSUE TITLE
iOS directory is not getting created

### ISSUE THREAD

**Issue by susaurabh-git** [orYoffe/create-react-native-web-app#110]
**Describe the bug**
iOS directory is not getting created

**To Reproduce**
1. npx create-react-native-web-app baseApp
2. cd baseApp
3. ls

**Expected behavior**
there should be ios directory inside application directory.

**Screenshots**
<img width="271" alt="Screen Shot 2021-09-23 at 12 29 21 PM" src="https://user-images.githubusercontent.com/20015708/134547708-c1479cdc-bca8-4c94-bc62-43371281db50.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 
 - Browser [safari]
 - Version 11.1

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS
 - Version 14.4

**Additional context**

**Comment by orYoffe** [comment]
hi @susaurabh-git did you use the package globally before? if so please uninstall it like this
npm uninstall -g create-react-native-web-app
and then try again.

I ran the command and it worked for me

**Comment by susaurabh-git** [comment]
Hi @orYoffe I don't have create-react-native-web-app globally. Still I ran 'npm uninstall -g create-react-native-web-app' then I tried npx create-react-native-web-app baseApp. still the same no "iOS" directory.

- node version v16.9.1
- npm version 7.21.1

Do you need any other information to help reproduce in your environment.

**Comment by orYoffe** [comment]
did you try with node 14? i didn't try 16 yet

**Comment by ThadeusAjayi** [comment]
@orYoffe I tried with node 14 didn't work

**Comment by orYoffe** [comment]
Thanks everyone.. I'm sorry for the long time it took me to take care of this.
I just published a new version with the ios folder back.. plz check and let me know as i don't have a mac with me at the moment and will get one only in a month.

Many thanks ❤️ really appreciate your help and plz let me know if the issue continues

**Comment by orYoffe** [comment]
I assume the issue has been resolved, closing since there was not answer.. plz reopen if you encounter the issue again
