### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by xinhash** [orYoffe/create-react-native-web-app#13]
I tried to include typescript following this  [link](https://facebook.github.io/react-native/blog/2018/05/07/using-typescript-with-react-native). 
But was facing a lot of issues. Has anybody tried implementing this ? 

Also create-react-app comes with ``--typescript`` support. Can the same be incorporated in this cli

**Comment by orYoffe** [comment]
closing until there will be more interest or some PR to get it starting

**Comment by johannb75** [comment]
Did you add this feature? If not, it would be really cool because now a lot of react-native developers use typescript.
Thanks

**Comment by orYoffe** [comment]
Since I don't do much typescript myself atm, it would take someone else to create a pr for an alternative template
