### ISSUE TITLE
Hot reloading for Web

### ISSUE THREAD

**Issue by iksent** [orYoffe/create-react-native-web-app#27]
**Describe the solution you'd like**
I want to have Hot Reloading for web out of the box.

**Describe alternatives you've considered**
May be we can integrate [React Hot Reload library](https://github.com/gaearon/react-hot-loader)? But which "Recipe" should we use? Can we use WebPack? Because also I want to use [RN vector icons](https://github.com/oblador/react-native-vector-icons#web-with-webpack) for Web, which is using WebPack.

**Offtop**
Your tool is very good - this is the only solution web+RN that works. Thank you for it.

**Comment by orYoffe** [comment]
Hi @iksent 

I checked the webpack dev server and it seems the create-react-app team already placed the `hot` option to true. I am not sure myself how to fix this.
https://github.com/VISI-ONE/create-react-native-web-app/blob/master/template/config/webpackDevServer.config.js#L61

any ideas?

**Comment by iksent** [comment]
Comment from your config: "...Note that only changes to CSS are currently hot reloaded. JS changes will refresh the browser...".
But [React Hot Loader](https://github.com/gaearon/react-hot-loader) provides the ability to reload hotly JS changes.

As a result of a "create-react-native-web-app" we have a project without WebPackConfig, is it right? So can we add this config or we should choose another [recipe](https://github.com/gaearon/react-hot-loader#recipes) of connecting "React Hot Loader"?
May be [React Dom from Hot library](https://github.com/hot-loader/react-dom)? It seems that connecting it is very easy process.

**Comment by iksent** [comment]
It works for me: https://github.com/gaearon/react-hot-loader#migrating-from-create-react-app

Without `npm run eject`
