### ISSUE TITLE
Better documentation 

### ISSUE THREAD

**Issue by orYoffe** [orYoffe/create-react-native-web-app#28]
**Is your feature request related to a problem? Please describe.**
Many users of the package encounter the same issues with es6/ios/android and since most of the advice are in the old closed issues, they either open a new issue or give up :(

**Describe the solution you'd like**
A few readme files for docs to explain these topics with link to from the main readme file:
- Running native on emulator and devices (Xcode and Android Studio)
- Testing
- Troubleshooting - like an F.A.Q about the various issues the users encounter
- Deployment - more how to build and less how to deploy to the various app stores
- other suggestions are welcome

**Describe alternatives you've considered**
Would  be nice to have a docs site with github pages but i would settle to start with readme files

**Additional context**
Common explanations about how to solve the new issues with Xcode and why we're not using the newest version of React Native. How to add es6 libraries to be compiled properly through webpack and others that react-native-web docs explain already

**Comment by iksent** [comment]
Nice tool for documentation: https://docsify.js.org/#/?id=docsify
It can combine github readme files.

**Comment by orYoffe** [comment]
@iksent thanks for the tip..

about react native version.. react-native-web repo already working on fixing it for v0.57 https://github.com/necolas/react-native-web/issues/1172
