### ISSUE TITLE
Support for react-native 0.59.0?

### ISSUE THREAD

**Issue by muhammadsr** [orYoffe/create-react-native-web-app#40]
I tried to upgrade to `react-native` `0.59.0` manually but I ran into issues with iOS.

**Comment by orYoffe** [comment]
react-native-web supports currently only react-native v55 https://github.com/necolas/react-native-web

**Comment by OKNoah** [comment]
> react-native-web supports currently only react-native v55 https://github.com/necolas/react-native-web

No, It supports most of 59.

**Comment by OKNoah** [comment]
@orYoffe Can we at least re-open this?

https://github.com/necolas/react-native-web/issues/1349#issuecomment-493221968

**Comment by orYoffe** [comment]
@OKNoah they still don't support v57 https://github.com/necolas/react-native-web/issues/1172

**Comment by SnakeHead** [comment]
We really need it to support 0.59+ in order to support 64 bit mobile apps for iOS and Android app stores otherwise the apps will be rejected after Aug 1.

**Comment by orYoffe** [comment]
@SnakeHead I would suggest to open an issue for https://github.com/necolas/react-native-web since that is the library that needs to add support

**Comment by OKNoah** [comment]
@oryoffe i’m using RNW with 0.59.8

**Comment by OKNoah** [comment]
RN isn't 100% with native. RNW isn't 100% with React. But we use these things because they offer benefits across the vast majority of use cases. I got this toolkit working with RN 0.59, so why won't won't you even accept pull requests? Even if they are `alpha` or `beta` releases, the ticket should be open.

**Comment by grit96** [comment]
@OKNoah have you got any details about how you got it working with 0.59?

**Comment by orYoffe** [comment]
@OKNoah Please supply some details about it.
Since RNW doesn't support the version I won't tell people that I do.
You can upgrade your package.json with new versions and see if in your case it breaks.. for some of us it does because of the lack of support

**Comment by princetoad1995** [comment]
@orYoffe Currently, RNW supported react-native version 0.59
https://github.com/necolas/react-native-web/issues/1389#issuecomment-507415885

**Comment by OKNoah** [comment]
I'm using react-native-web (RNW) with `0.61.2` :)

**Comment by orYoffe** [comment]
Working on a new

> RN isn't 100% with native. RNW isn't 100% with React. But we use these things because they offer benefits across the vast majority of use cases. I got this toolkit working with RN 0.59, so why won't you even accept pull requests? Even if they are `alpha` or `beta` releases, the ticket should be open.

I accept pull requests happily
