### ISSUE TITLE
production babel build messes code

### ISSUE THREAD

**Issue by sirpy** [orYoffe/create-react-native-web-app#41]
**Describe the bug**
Production build doesn't work where react-native-web animated is used.
If BABEL_ENV is set to development it works fine.
This was tested for both react-native-elements Input and react-native-paper Button
which both uses animation.

**To Reproduce**
npm i react-native-elements react-native-vector-icons
npm i -g serve
add this to App.js render method
```
<Input ref = { ref => this.input = ref } shake="true" placeholder="test" onChange={ x=> this.input.shake()}/>
```
npm run build
serve -s build
open web page and you'll see it doesnt render and an error in console.

**Expected behavior**
Work the same as development build and the same as CREATE-REACT-APP
npm run web works as expected
On create-react-app this works as expected also on production build
It seems something in the build definitions/ babel plugins/version  is causing it

**Desktop (please complete the following information):**
 - OS: win/os
 - Browser chrome

**Comment by orYoffe** [comment]
Hi @sirpy,

then issue seems to be with another package. In the boilerplate we use animations and after testing myself I saw it working in production build with animations.

simply install and create a project with our package
npm run build
serve -s build

and see the button activates the animation fine on windows.

I would suggest to open an issue for react-native-elements maybe the issue is on their side.
also an error stack log of what you got in the console would help to figure out the problem further

**Comment by sirpy** [comment]
Hey  @orYoffe 
2 things make me still think this is an issue on your side
1. it works just fine when using create-react-app boilerplate and building in production mode
2. it happens both with react-native-elements(Input) AND react-native-paper (Button)

I think this should be reopened

**Comment by sirpy** [comment]
you can find the stacktrace from the same bug I opened for react-native-web
https://github.com/necolas/react-native-web/issues/1306

**Comment by orYoffe** [comment]
opened until further inspection

**Comment by geminiyellow** [comment]
maybe cause by `create-react-app` , i do it in pure `CRA`, also same error.

**Comment by sirpy** [comment]
@geminiyellow can you share a minimal example that gives you that error? doesn't happen to me on CRA.

**Comment by geminiyellow** [comment]
have no idea. i will try it again. maybe i can find what has happened today.

**Comment by sirpy** [comment]
someone reported that using commonjs solves the issue

https://github.com/necolas/react-native-web/issues/1306#issuecomment-498901686

['react-native-web', { commonjs: true }],

**Comment by geminiyellow** [comment]
opps, why coomonjs ?

**Comment by sirpy** [comment]
@geminiyellow i have no idea, didnt try it, just reported what I read. could be that there's some overriding of functions with similar names that doesnt happen with commonjs style compilation

**Comment by orYoffe** [comment]
@sirpy this issue might help https://github.com/orYoffe/create-react-native-web-app/issues/64
but otherwise i would open an issue for react-native-element maybe they can help
