### ISSUE TITLE
npx react-native-rename breaks the app

### ISSUE THREAD

**Issue by belizar** [orYoffe/create-react-native-web-app#51]
Look at the image,
![image](https://user-images.githubusercontent.com/37871475/64265412-39a0b700-cf09-11e9-8549-c5b5f8086f05.png)

**Comment by orYoffe** [comment]
this is because of the renaming library.. if you'd like to work on it it's a good first issue. thanks for sharing :)

I hope it didn't stop you from coding.
you can install the dependencies yourself by doing `npm i` or `yarn` inside the project folder and start coding away :)

**Comment by giliyoffe** [comment]
@belizar can you still reproduce this issue?
I can not reproduce it.
@orYoffe did you fix it?
thanks

**Comment by orYoffe** [comment]
closing issue since nothing happened with this plus doesn't seem like i can reproduce it
