### ISSUE TITLE
React-native at 55.x

### ISSUE THREAD

**Issue by jonsmirl** [orYoffe/create-react-native-web-app#61]
This tool does not function on macOS Catalina without upgrading to newer react-native. 

Edit: the problem is Xcode, not Catalina. Back off to Xcode 10.3 and it will work again. react-native 0.61 or better works on Xcode 11.

**Comment by orYoffe** [comment]
you can try to update the dependencies and see if it works.. there are supposed to be some bugs but not for everyone. I just didn't have a lot of time right now to build a new version
