### ISSUE TITLE
unhandled js exception: getPropertyAsObject: property

### ISSUE THREAD

**Issue by macroswang** [orYoffe/create-react-native-web-app#63]
hi:
 I run : yarn ios

get exception:
unhandled js exception: getPropertyAsObject: property '__fbRequireBatchedBridge' is not an Object

：(  
please tell me how to resolve??
thx

**Comment by orYoffe** [comment]
sorry i need more details to understand the issue.
Could you try to open Xcode and run it there.. usually it's better for the first time. BTW if you don't use a mac you can't develop IOS, at least not with this package.

closing till further details. Good luck :)
