### ISSUE TITLE
React native 0.61.0

### ISSUE THREAD

**Issue by arshidkv12** [orYoffe/create-react-native-web-app#65]
It is not working with latest react native version 0.61.0

**Comment by arshidkv12** [comment]
It is working with https://github.com/orYoffe/create-react-native-web-app but version is 0.55.0

create-react-app also working

**Comment by barakoles** [comment]
@arshidkv12 Any updates on this? Did you manage to upgrade react-native? I'll try now

**Comment by orYoffe** [comment]
solved in new version 0.15.0. Please feel free to open an issue if you see anything broken 🙏
