### ISSUE TITLE
Android doesn't build

### ISSUE THREAD

**Issue by MattGibz** [orYoffe/create-react-native-web-app#78]
**Describe the bug**
Running "npm run android" results in an error 

**To Reproduce**
1. Follow the [installation guide](https://github.com/orYoffe/create-react-native-web-app#installation)
2. "npm run web" works
3. "npm run android" results in an error

**Expected behavior**
Application builds and runs in Android emulator

**Screenshots**
![image](https://user-images.githubusercontent.com/1053147/82465485-5546f000-9a8d-11ea-87a2-9393f14256a4.png)

**Comment by orYoffe** [comment]
Hi @MattGibz , 
did you follow the environment setup instruction of react native for ios and android first or is it the first time you try react native?
https://reactnative.dev/docs/environment-setup

**Comment by MattGibz** [comment]
Yes I have react native environment setup. I can successfully run a fresh react native project in Android.

**Comment by orYoffe** [comment]
Ok, thanks for opening the issue. 
Have you tried running `npm run start-clean` and then run `npm run android`?
If that doesn't work, can you run `react-native info` to include these results here

**Comment by MattGibz** [comment]
Thanks for the responses @orYoffe. I ended up implementing it a slightly different way and I have my code working now.

**Comment by orYoffe** [comment]
Hi @MattGibz that's great. 

Mind sharing what it was? Maybe it's worth sharing for future users

**Comment by orYoffe** [comment]
הפעם קיבלתי, אולי בגלל שהוא תייג אותי

**Comment by MattGibz** [comment]
@orYoffe Sure thing! I created a [repo](https://github.com/MattGibz/ReactNativeWebMobileTemplate) that you can either clone or follow the instructions in the README
