### ISSUE TITLE
React-native-vector-icon can not run get Error 

### ISSUE THREAD

**Issue by MahmoudShaeer** [orYoffe/create-react-native-web-app#83]
how can correct steeps to link vector icon with web by steps please with last version of create-react-native-web-app 
and if i want add react-native-animatable whats should i do ?

**Comment by orYoffe** [comment]
you need to add ES6 modules libraries in the webpack config: https://github.com/orYoffe/create-react-native-web-app/issues/64#issuecomment-556300812
