### ISSUE TITLE
Deprecated dependencies (developer menu doesn't open)

### ISSUE THREAD

**Issue by johannb75** [orYoffe/create-react-native-web-app#85]
Hi @orYoffe,
First: This is a really cool library.
Second:
Could you update the dependencies ?
When I run the `npm run ios` command, it opens an old version of metro. Because of this, I can't open the developer menu.
And when I'm initializing the app with `npx`, it shows me a bunch of warnings containing deprecated dependencies. 
```cmd
npm WARN deprecated deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated @types/testing-library__dom@7.5.0: This is a stub types definition. testing-library__dom provides its own type definitions, so you do not need this installed.
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
```
Thanks

**Comment by orYoffe** [comment]
Hi @johannb75 ,

Thanks for bringing this up. 
I currently don't have a mac with me but will in a few weeks.
If you or anybody you know would like to contribute by trying to update them would be great to accept a PR. Basically need to update the template file with a mix of CRA and CRNA

Otherwise it will take me a while to update and then make sure it works properly on ios in order to release.

Many thanks :heart:

**Comment by johannb75** [comment]
Ok, thanks a lot !
I'll try to help.

**Comment by orYoffe** [comment]
That would be great. I'm here to help if you need.

About Yarn:
You could add it like in create-react-app cli https://github.com/facebook/create-react-app/blob/master/packages/create-react-app/createReactApp.js#L274
I would prefer this to be a separate PR if you don't mind, since that would be an additional feature

**Comment by orYoffe** [comment]
Hi @johannb75,

create-react-app just released version 4.
I think I'll need anyway to regenerate the template and get both CRA and CRNA merged again.. just wanted to point out.. since that will override your changes probably.. unless you want to do all of that 😅

**Comment by orYoffe** [comment]
Dependencies updated and yarn can be used if installed in new version 0.16.0

**Comment by orYoffe** [comment]
@johannb75 would love to hear if it works for you on ios

**Comment by johannb75** [comment]
Hi @orYoffe just wanted to say everything works great but there is an error with cocoapods installation. It seems that I'm not the only one to have this issue. #86 
Thanks
