### ISSUE TITLE
Running `npx crnwa myApp` doesnt work.

### ISSUE THREAD

**Issue by idkjs** [orYoffe/create-react-native-web-app#88]
**Describe the bug**
Running `npx crnwa myApp` produces and empty myApp folder.
Running `npx create-react-native-web-app myApp` seems to work ok.

An fyi.

**Comment by orYoffe** [comment]
Hi @idkjs 
Thanks for opening the issue and reporting. Could you specify what doesn't work? A few more details on environment and other details would help.

Two ways I would ask to try to solve or clarify the issue if you will.
1) if you have installed create-react-native-web-app globally before please run `npm uninstall -g create-react-native-web-app` to remove it 
2) try running `npx crnwa --version` the output should be `0.16.2` the current version

**Comment by idkjs** [comment]
I just went back through it to get you some info. Works just fine. No idea what I did before. Thank you.
