### ISSUE TITLE
Add web support to an existence react native project

### ISSUE THREAD

**Issue by samaneh-kamalian** [orYoffe/create-react-native-web-app#97]
How can use your module for an existence react native project?
my react native project support ios and android and now I want to add web support. I use webpack, but there are lots of problem.

**Comment by orYoffe** [comment]
There are guides in the react native web docs that are pretty useful to follow.. this repo starts new projects, you could also start a new one and try adding the code for web but i wouldn't recommend that. The docs are pretty good :)
https://necolas.github.io/react-native-web/docs/installation/
